name: 'credit_domino'
version: '1.0.0'
config-version: 2

profile: 'credit_domino'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  credit_domino:
    staging:
      materialized: view
    marts:
      materialized: table
      fct_scoring_log:
        materialized: incremental
